			var UserSession = (function(){

					var public = {};
					var private = {
						sessionName : "pontis_session"
					};

					private.login = function(fields){
						var currentSession = private.getUser();

						var userSession = {
							lastChange: new Date().valueOf(),
							sessionFields:fields
						}

						var merged = $.extend( true, currentSession,userSession );

						if(currentSession && currentSession.sessionFields){
							for(var curField in currentSession.sessionFields){
								merged.sessionFields.push(currentSession.sessionFields[curField]);
							}
						}
						

						var str = JSON.stringify(merged);
						window.localStorage.setItem(private.sessionName,str);
						return private.getUser();
					}

					private.logout = function(fields){
						window.localStorage.clear();
					}

					private.getUser = function(){
						try{
							answer = JSON.parse(window.localStorage.getItem(private.sessionName));
						}catch(e){}

						return answer;
					}

					private.hasFieldInSession = function(fieldName){
						var user = private.getUser();
						var bool = false;
						if(user && user.sessionFields){
							for(var curField in user.sessionFields){
								if( user.sessionFields[curField]['name'] == fieldName ){
									bool = true;
								}
							}
						}
						return bool;
					}

					public.has = function(fieldName){
						return private.hasFieldInSession(fieldName);
					}

					public.logInUser = function(fieldsArr){
						private.login(fieldsArr);
						return private.getUser();
					}

					public.getUserInfo = function(){
						return private.getUser();
					}

					return public;
			})();


			var API = (function(){
				var public = {}

				public.endPoints = {
					// Parameters
					// subscriberId
					// the id generated by the website
					// required
					// msisdn 
					// The phone number submitted in sign in form
					// optional
					'offers':{url:'/mockdata/get_offers.json',type:"get"},

					// Show offer
					// GET
					// /show-offer.php

					// Definition
					// http://www.pontisnewcom.com/api/show-offer.php

					// Parameters
					// subscriberId
					// the id generated by the website
					// required	
					//       2) 	msisdn 
					// The phone number submitted in sign in form
					// Optional
					//       3)   maCode
					// 	The maCode (returned in the get-offers api)

					'showOffer':{url:'show-offer.php',type:"get"},


					// POST
					// /select-offer.php

					// Call select offer only if the offer has the parameter
					// isRequired = true

					// Definition
					// http://www.pontisnewcom.com/api/select-offer.php

					// Parameters
					// subscriberId
					// the id generated by the website
					// required	
					//       2) 	msisdn 
					// The phone number submitted in sign in form
					// Optional
					//       3)   maCode
					// 	The maCode (returned in the get-offers api)
					'selectOffer':{url:'select-offer.php',type:"post"},

					// Update subscriber
					// POST
					// /update-subscriber.php

					// Definition
					// http://www.pontisnewcom.com/api/update-subscriber.php

					// Parameters
					// subscriberId
					// required
					// Referer : url referer
					// required
					//       3)   requiredFields 
					// 	Array of required fields. Json as string
					// 	Example:
					// 	“[ { \”name\” : “\my name\” }, { \”email\” : \”myemail@mail.com\” } ]”

					// Response
					// {
					// 	“Status” : {
					// 		“Success” : “true”
					// }
					// }

					'updateSubscriber':{url:'update-subscriber.php',type:"post"},



					// Optin (select offer);
					// POST
					// /optin.php

					// Definition
					// http://www.pontisnewcom.com/api/optin.php

					// Parameters
					// Msisdn
					// 	optional
					// subscriberId
					// optinCode

					// Response
					// {
					// 	“Status” : {
					// 		“Success” : “true”
					// }
					// }

					'optIn':{url:'optin.php',type:"post"},

					/*
					Browse
					POST
					/browse.php

					Definition
					http://www.pontisnewcom.com/api/browse.php


					Parameters
					Msisdn
						optional
					subscriberId
					tag
					url

					Response
					{
						“Status” : {
							“Success” : “true”
					}
					}
					*/
					'browse':{url:'browse.php',type:"post"},


				}

				return public;

			})();
		